- name: install firewalld
  yum:
    name:   firewalld
    state: latest

- name: service firewalld
  service:
    name:    firewalld
    enabled: True

- name: Configure firewalld - defaults
  firewalld:
    port:      "{{ item.port }}/{{ item.protocol }}"
    zone:      "{{ item.zone }}"
    source:    "{{ item.source | default('0.0.0.0/0')}}"
    permanent: true
    state:     enabled
  notify:    "restart firewalld"
  with_items:
    - "{{ firewalld.configuration.input_ports     }}"
  when:
    firewalld is defined and
    firewalld.configuration is defined and
    firewalld.configuration.input_ports is defined

- name: Configure firewalld - Extras
  firewalld:
    port:      "{{ item.port }}/{{ item.protocol }}"
    zone:      "{{ item.zone }}"
    source:    "{{ item.source | default('0.0.0.0/0')}}"
    permanent: true
    state:     enabled
  notify:    "restart firewalld"
  with_items:
    - "{{ firewalld.configuration.extra_ports }}"
  when:
    firewalld is defined and
    firewalld.configuration is defined and
    firewalld.configuration.extra_ports is defined
